#!/usr/bin/env python3

"""
Description: https://projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Solution: 4613732
"""


def evenFibSum(n):
    if n < 2 or n < 0:
        return 0
    x0, x1 = 0, 2
    s = x0 + x1
    while True:
        tmp = x0 + x1 * 4
        if tmp >= n:
            break
        s += tmp
        x0, x1 = x1, tmp
    return s


if __name__ == "__main__":
    sol = evenFibSum(int(4e6))
    print(sol)
